# Generated by Django 4.2 on 2025-04-16 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup', models.BooleanField(default=True, verbose_name='Автоматичне резервне копіювання')),
                ('backup_frequency', models.PositiveIntegerField(default=1, verbose_name='Частота резервного копіювання (днів)')),
                ('last_backup', models.DateTimeField(blank=True, null=True, verbose_name='Останнє резервне копіювання')),
                ('backup_location', models.CharField(default='backups/', max_length=255, verbose_name='Місце зберігання резервних копій')),
            ],
            options={
                'verbose_name': 'Налаштування резервного копіювання',
                'verbose_name_plural': 'Налаштування резервного копіювання',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва культури')),
            ],
            options={
                'verbose_name': 'Культура',
                'verbose_name_plural': 'Культури',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Одиниця виміру')),
            ],
            options={
                'verbose_name': 'Одиниця виміру',
                'verbose_name_plural': 'Одиниці виміру',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Прийнято'), ('successful', 'Успішно'), ('canceled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна сума')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип упаковки')),
            ],
            options={
                'verbose_name': 'Тип упаковки',
                'verbose_name_plural': 'Типи упаковки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Назва продукту')),
                ('real_name', models.CharField(max_length=200, verbose_name='Назва справжня')),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер лоту')),
                ('import_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Імпорт назва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис товару')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наявності')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('packages_count', models.PositiveIntegerField(default=0, verbose_name='Кількість упаковок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото товару')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('has_variations', models.BooleanField(default=False, verbose_name='Має варіації')),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.culture', verbose_name='Культура')),
                ('measurement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.measurementunit', verbose_name='Одиниця виміру')),
                ('package_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.packagetype', verbose_name='Тип упаковки')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Назва продукту')),
                ('real_name', models.CharField(max_length=200, verbose_name='Назва справжня')),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер лоту')),
                ('import_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Імпорт назва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис товару')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наявності')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('packages_count', models.PositiveIntegerField(default=0, verbose_name='Кількість упаковок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото товару')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('variation_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва варіації')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул')),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.culture', verbose_name='Культура')),
                ('measurement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.measurementunit', verbose_name='Одиниця виміру')),
                ('package_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.packagetype', verbose_name='Тип упаковки')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='warehouse.product', verbose_name='Основний товар')),
            ],
            options={
                'verbose_name': 'Варіація товару',
                'verbose_name_plural': 'Варіації товарів',
                'unique_together': {('parent_product', 'variation_name')},
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('value', models.CharField(max_length=255, verbose_name='Значення')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Системний параметр',
                'verbose_name_plural': 'Системні параметри',
            },
        ),
        migrations.CreateModel(
            name='ProductVariationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_variations/', verbose_name='Фото товару')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.productvariation', verbose_name='Варіація товару')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('incoming', 'Надходження'), ('outgoing', 'Видача'), ('return', 'Повернення'), ('write_off', 'Списання')], max_length=20, verbose_name='Тип руху')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер документу')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.order', verbose_name='Замовлення')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Виконав')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Рух товару',
                'verbose_name_plural': 'Рух товарів',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото товару')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товарів',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за одиницю')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна ціна')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар у замовленні',
                'verbose_name_plural': 'Товари у замовленні',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_expected', models.PositiveIntegerField(default=0, verbose_name='Очікувана кількість')),
                ('quantity_actual', models.PositiveIntegerField(default=0, verbose_name='Фактична кількість')),
                ('difference', models.IntegerField(default=0, verbose_name='Відхилення')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Виконав')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Інвентаризація',
                'verbose_name_plural': 'Інвентаризації',
            },
        ),
    ]
