# Generated by Django 4.2 on 2025-04-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default=1, max_length=100, verbose_name='Код товару'),
            preserve_default=False,
        ),
    ]
