# Generated by Django 4.2 on 2025-04-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_productvariation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Прийнято'), ('successful', 'Успішно'), ('canceled', 'Скасовано')], default='accepted', max_length=20, verbose_name='Статус'),
        ),
    ]
