# Generated by Django 4.2 on 2025-04-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('successful', 'Успішно'), ('canceled', 'Скасовано')], default='accepted', max_length=20, verbose_name='Статус'),
        ),
    ]
