# Generated by Django 4.2 on 2025-04-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='real_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Назва справжня'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='real_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Назва справжня'),
        ),
    ]
