# Generated by Django 4.2 on 2025-04-19 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0008_alter_product_real_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип руху')),
            ],
            options={
                'verbose_name': 'Тип руху',
                'verbose_name_plural': 'Типи руху',
            },
        ),
        migrations.CreateModel(
            name='ProductIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Загальна кількість')),
                ('total_packages_count', models.PositiveIntegerField(default=0, verbose_name='Загальна кількість упаковок')),
                ('movement_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.movementtype', verbose_name='Тип руху')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Виконав')),
            ],
            options={
                'verbose_name': 'Оприбуткування товару',
                'verbose_name_plural': 'Оприбуткування товарів',
            },
        ),
        migrations.CreateModel(
            name='ProductIncomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('packages_count', models.PositiveIntegerField(verbose_name='Кількість упаковок')),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер лоту')),
                ('measurement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.measurementunit', verbose_name='Одиниця виміру')),
                ('package_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.packagetype', verbose_name='Тип упаковки')),
                ('product_income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.productincome', verbose_name='Оприбуткування товару')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.productvariation', verbose_name='Варіація товару')),
            ],
            options={
                'verbose_name': 'Варіація товару в оприбуткуванні',
                'verbose_name_plural': 'Варіації товарів в оприбуткуванні',
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductMovement',
        ),
    ]
