# Generated by Django 4.2 on 2025-04-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_movementtype_productincome_productincomeitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementtype',
            name='name',
            field=models.CharField(choices=[('incoming', 'Оприбуткування'), ('inventory', 'Інвентаризація')], max_length=100, verbose_name='Тип руху'),
        ),
    ]
