# Generated by Django 4.2 on 2025-04-19 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_alter_productincome_movement_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва параметра')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.systemparam', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Системний параметр',
                'verbose_name_plural': 'Системні параметри',
            },
        ),
    ]
