# Generated by Django 4.2 on 2025-04-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_systemparam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='culture',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('successful', 'Успішно'), ('canceled', 'Скасовано')], default='successful', max_length=20, verbose_name='Статус'),
        ),
    ]
