# Generated by Django 4.2 on 2025-04-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_remove_productvariation_culture_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('incoming', 'Оприбуткування'), ('outgoing', 'Списання')], max_length=100, verbose_name='Тип руху')),
            ],
            options={
                'verbose_name': 'Тип руху товарів',
                'verbose_name_plural': 'Типи руху товарів',
            },
        ),
        migrations.AlterField(
            model_name='productincome',
            name='movement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.movementtypes', verbose_name='Тип руху'),
        ),
    ]
