# Generated by Django 4.2 on 2025-04-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_movementtypes_alter_productincome_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincomeitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouse.product', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
