# Generated by Django 4.2 on 2025-04-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_productincomeitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincomeitem',
            name='product',
        ),
    ]
