# Generated by Django 4.2 on 2025-04-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_remove_productincomeitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincome',
            name='movement_type',
            field=models.CharField(default='incoming', max_length=100, verbose_name='Тип накладної'),
        ),
        migrations.DeleteModel(
            name='MovementTypes',
        ),
    ]
