# Generated by Django 4.2 on 2025-04-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_alter_productincome_movement_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productincome',
            options={'verbose_name': 'Прибуткова накладна', 'verbose_name_plural': 'Прибуткові накладні'},
        ),
        migrations.AlterModelOptions(
            name='productincomeitem',
            options={'verbose_name': 'Варіація в прибутковій накладній', 'verbose_name_plural': 'Варіації в прибутковій накладній'},
        ),
    ]
