# Generated by Django 4.2 on 2025-04-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_alter_productincome_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemparam',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='warehouse.systemparam', verbose_name='Параметр'),
        ),
    ]
