# Generated by Django 4.2 on 2025-04-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_alter_systemparam_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemparam',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='Має дочірні параметри'),
        ),
    ]
