# Generated by Django 4.2 on 2025-04-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_remove_systemparam_has_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemparam',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='Має дочірні параметри'),
        ),
    ]
