# Generated by Django 4.2 on 2025-04-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_systemparam_has_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemparam',
            name='has_children',
        ),
    ]
