# Generated by Django 4.2 on 2025-04-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_remove_systemparam_has_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvetoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('fact_quantity', models.PositiveIntegerField(default=0, verbose_name='Фактична кількість')),
                ('packages_count', models.PositiveIntegerField(default=0, verbose_name='Кількість упаковок')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.inventory', verbose_name='Інвентаризація')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.productvariation', verbose_name='Варіація товару')),
            ],
            options={
                'verbose_name': 'Інвентаризація',
                'verbose_name_plural': 'Інвентаризації',
            },
        ),
    ]
