# Generated by Django 4.2 on 2025-04-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_invetoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('fact_quantity', models.PositiveIntegerField(default=0, verbose_name='Фактична кількість')),
                ('difference', models.IntegerField(default=0, verbose_name='Відхилення')),
                ('packages_count', models.PositiveIntegerField(default=0, verbose_name='Кількість упаковок')),
            ],
            options={
                'verbose_name': 'Інвентаризація',
                'verbose_name_plural': 'Інвентаризації',
            },
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='difference',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity_actual',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity_expected',
        ),
        migrations.AddField(
            model_name='inventory',
            name='movement_type',
            field=models.CharField(default='inventory', max_length=100, verbose_name='Тип накладної'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.DeleteModel(
            name='InvetoryItem',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.inventory', verbose_name='Інвентаризація'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.productvariation', verbose_name='Варіація товару'),
        ),
    ]
