# Generated by Django 4.2 on 2025-04-27 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_inventoryitem_remove_inventory_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='packages_count',
        ),
    ]
