# Generated by Django 4.2 on 2025-04-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0026_remove_inventoryitem_packages_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='movement_type',
            field=models.CharField(blank=True, default='inventory', max_length=100, null=True, verbose_name='Тип накладної'),
        ),
    ]
