# Generated by Django 5.1.7 on 2025-04-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0027_alter_inventory_movement_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductInventory",
        ),
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={
                "verbose_name": "Варіація в інвентаризації",
                "verbose_name_plural": "Варіації в інвентаризації",
            },
        ),
    ]
