# Generated by Django 5.1.7 on 2025-05-07 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0029_migrate_orderitem_to_variation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Варіація у замовленні",
                "verbose_name_plural": "Варіації у замовленні",
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_variation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.productvariation",
                verbose_name="Варіація товару",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.product",
                verbose_name="Товар",
            ),
        ),
        migrations.CreateModel(
            name="ProductMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        default="movement", max_length=100, verbose_name="Тип руху"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Виконав",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рух товарів",
                "verbose_name_plural": "Рух товарів",
            },
        ),
    ]
