# Generated by Django 5.1.7 on 2025-05-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "warehouse",
            "0030_alter_orderitem_options_orderitem_product_variation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
    ]
