# Generated by Django 5.1.7 on 2025-05-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0031_remove_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.productvariation', verbose_name='Варіація товару'),
        ),
    ]
