# Generated by Django 4.2 on 2025-05-07 20:15

from django.db import migrations, models
import django.db.models.deletion

def migrate_user_to_created_by(apps, schema_editor):
    Order = apps.get_model('warehouse', 'Order')
    for order in Order.objects.all():
        order.created_by = order.user
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0032_make_product_variation_non_nullable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='created_by',
        ),
    ] 